import { ModelOption } from "@/types/settings";

export const AVAILABLE_MODELS: ModelOption[] = [
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B (Clinical Reasoning)",
    provider: "Groq Cloud",
    contextWindow: 131072,
    description: "Highest medical reasoning accuracy, guideline grounding, and complex differential diagnosis.",
    descriptionAr: "أعلى دقة في الاستدلال السريري، وتطابق الاستشهادات الطبية، والتحليل التفريقي المعقد.",
    badge: "Recommended",
    isDefault: true,
    recommendedFor: "Clinical Guidelines & Reasoning",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT-OSS 20B (Fast & Balanced)",
    provider: "Groq Cloud",
    contextWindow: 65536,
    description: "Ultra-fast response latency and efficient medical query translation.",
    descriptionAr: "سرعة فائقة في المعالجة والترجمة الطبية الدقيقة.",
    badge: "Ultra Fast",
    isDefault: false,
    recommendedFor: "Translation & Instant Summaries",
  },
  {
    id: "qwen/qwen3.6-27b",
    name: "Qwen 3.6 27B (Multilingual)",
    provider: "Groq Cloud",
    contextWindow: 32768,
    description: "Strong bilingual Arabic/English comprehension with high precision medical fluency.",
    descriptionAr: "كفاءة لغوية متقدمة في الفهم الطبي الثنائي للعربية والإنجليزية.",
    badge: "Bilingual Pro",
    isDefault: false,
    recommendedFor: "Arabic Nuances",
  },
  {
    id: "allam-2-7b",
    name: "Allam 2 7B (Arabic Native)",
    provider: "Groq Cloud",
    contextWindow: 8192,
    description: "Arabic-native specialized foundational model.",
    descriptionAr: "نموذج لغوي تأسيسي متخصص باللغة العربية.",
    badge: "Arabic Native",
    isDefault: false,
    recommendedFor: "Arabic Synthesis",
  },
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B (Versatile)",
    provider: "Groq Cloud",
    contextWindow: 131072,
    description: "Meta's flagship open-weights model for general clinical RAG.",
    descriptionAr: "نموذج ميتا الرائد للاسترجاع السريري العام.",
    badge: "Versatile",
    isDefault: false,
    recommendedFor: "General Medical QA",
  }
];
