import { RubricCriterion } from "@/types/rag";

export const HACKATHON_RUBRIC: RubricCriterion[] = [
  {
    id: "retrieval_quality",
    title: "1. Retrieval Quality",
    titleAr: "1. جودة الاسترجاع الدلالي",
    maxPoints: 22,
    description: "Relevance of top-k retrieved chunks, section-aware chunking, embedding transparency, and Precision@k.",
    descriptionAr: "مدى صلة المقاطع المسترجعة بالسؤال السريري، التقطيع المبني على أقسام الأدلة، وشفافية الاسترجاع.",
    checks: [
      "Top-k chunks specifically responsive to clinical query",
      "Section-aware and guideline-structured chunking",
      "Retrieved evidence previewed before/alongside answer generation",
      "Precision@k verified against benchmark test questions",
    ],
    checksAr: [
      "صلة المقاطع المسترجعة المباشرة بالسؤال السريري المطروح",
      "تقطيع النصوص بناءً على أقسام الإرشادات الطبية وليس عشوائياً",
      "عرض شفاف للأدلة المسترجعة ودرجات التشابه قبل/مع التوليد",
      "دقة الاسترجاع Precision@k مثبتة على بنك الأسئلة السريرية",
    ],
  },
  {
    id: "faithfulness",
    title: "2. Answer Grounding & Faithfulness",
    titleAr: "2. موثوقية وتأصيل الإجابة بالأدلة",
    maxPoints: 18,
    description: "Accuracy of citations (doc, section, page), absence of hallucinations, and preserving recommendation strength.",
    descriptionAr: "دقة الاستشهادات (المستند، القسم، الصفحة)، انعدام الهلوسة، والحفاظ على قوة التوصية (قوية/مشروطة).",
    checks: [
      "Every claim backed by cited guideline excerpt",
      "Exact document, section, and page number citations",
      "No hallucinated claims outside retrieved context",
      "Distinction between Strong vs Conditional recommendations",
    ],
    checksAr: [
      "كل معلومة سريرية مدعومة باقتباس صريح من الدليل المعتمد",
      "استشهادات دقيقة تشير لرقم الصفحة والقسم في NICE / WHO",
      "انعدام تام للمعلومات غير المؤصلة أو الهلوسة الطبية",
      "الحفاظ على قوة التوصية الأصلية (إلزامية، قوية، أو خيار مشروط)",
    ],
  },
  {
    id: "architecture",
    title: "3. System Architecture & Full-Stack",
    titleAr: "3. المعمارية البرمجية والتكامل الكامل",
    maxPoints: 15,
    description: "Clear layer separation (ingestion, retrieval, generation, safety), modular code, error resilience.",
    descriptionAr: "فصل واضح بين طبقات المعالجة، كود نظيف وقابل للصيانة (SOLID)، ومعالجة مرنة للأخطاء.",
    checks: [
      "Clean separation between retrieval, LLM, translation, and UI layers",
      "Swappable vector backend and LLM provider endpoints",
      "Resilient error handling and graceful fallbacks",
      "Live interactive web interface ready for deployment",
    ],
    checksAr: [
      "فصل تام بين طبقات الترجمة، الاسترجاع، التوليد، وواجهة المستخدم",
      "إمكانية تبديل مزودات الذكاء الاصطناعي وقواعد الفيكتور بسهولة",
      "معالجة متقدمة لجميع حالات الأخطاء وانقطاع الاتصال",
      "واجهة تفاعلية حية متصلة بالـ API وجاهزة للنشر المباشر",
    ],
  },
  {
    id: "metrics",
    title: "4. Evaluation & Metrics Implementation",
    titleAr: "4. التقييم والمقاييس السريرية",
    maxPoints: 10,
    description: "Appropriate RAG metrics (Precision@k, Faithfulness, Latency trade-offs, confidence threshold).",
    descriptionAr: "مقاييس دقيقة لمنظومة الـ RAG (الدقة، التأصيل، زمن الاستجابة، ونسب الثقة).",
    checks: [
      "Confidence score calculated for each clinical answer",
      "Latency breakdown (Retrieval vs Generation vs Translation)",
      "Token usage & context budget awareness",
      "Continuous metrics inspection drawer for clinicians",
    ],
    checksAr: [
      "حساب مؤشر التأصيل والثقة السريرية لكل إجابة",
      "تحليل تفصيلي لزمن الاستجابة (الترجمة + الاسترجاع + التوليد)",
      "تتبع استهلاك الـ Tokens وميزانية السياق",
      "لوحة مقاييس شفافة للمقيمين والأطباء",
    ],
  },
  {
    id: "safety",
    title: "5. Clinical Safety & Responsible AI",
    titleAr: "5. الأمان السريري والذكاء الاصطناعي المسؤول",
    maxPoints: 8,
    description: "Explicit refusal when evidence is insufficient, visible warnings against over-confidence, clinical disclaimers.",
    descriptionAr: "الامتناع الصريح عن التخمين عند نقص الأدلة، تحذيرات الأمان، والتأكيد على دور الطبيب.",
    checks: [
      "Explicit refusal badge if similarity < confidence threshold",
      "Clear clinical decision support disclaimers",
      "Pregnancy contraindication safety alerts (ACEi/ARBs/Statins)",
      "Clear non-substitute for physician judgment notice",
    ],
    checksAr: [
      "تنبيه صريح عند عدم كفاية الأدلة ورفض التخمين السريري",
      "تنبيهات سلامة بارزة لموانع الاستخدام في الحمل والأمراض المزمنة",
      "إشعار واضح بأن النظام داعم للقرار وليس بديلاً عن الطبيب",
    ],
  },
  {
    id: "presentation",
    title: "6. Presentation & Live UX Demo",
    titleAr: "6. العرض وتجربة الاستخدام الحية",
    maxPoints: 17,
    description: "Clarity of interface, fast source lookup for busy clinicians, bilingual RTL/LTR, dark/light theme polish.",
    descriptionAr: "سهولة وسرعة وصول الطبيب للمصدر، دعم العربية والإنجليزية مع RTL، وتصميم سريري مريح.",
    checks: [
      "Clinicians can verify source in <2 seconds via citation pills",
      "Flawless Arabic (RTL) & English (LTR) bidirectional support",
      "Smooth dark/light clinical themes",
      "20 Pre-loaded clinical sample questions for 1-click testing",
    ],
    checksAr: [
      "إمكانية التحقق من المصدر خلال ثانيتين عبر كبسولات الاستشهاد",
      "تبديل فوري وسلس بين العربية (RTL) والإنجليزية (LTR)",
      "أوضاع داكنة وفاتحة متقنة ومريحة للقراءة السريرية الطويلة",
      "20 سؤال سريري جاهز للاختبار الفوري بنقرة واحدة",
    ],
  },
  {
    id: "innovation",
    title: "7. Innovation & Out-of-the-Box Thinking",
    titleAr: "7. الابتكار والحلول الإبداعية",
    maxPoints: 10,
    description: "Cross-lingual embedding pipeline, differential guideline comparison (WHO vs NICE), interactive RAG inspector.",
    descriptionAr: "خط الترجمة المزدوج للبحث بالفيكتور، المقارنة التفريقية بين الأدلة، ولوحة فحص الـ RAG.",
    checks: [
      "Cross-lingual query translation pipeline for vector embeddings",
      "WHO vs NICE side-by-side guideline comparison mode",
      "Real-time RAG chunk similarity inspector drawer",
    ],
    checksAr: [
      "خط ترجمة مزدوج ذكي يربط الاستفسارات العربية بالـ Embeddings الإنجليزية",
      "لوحة مقارنة تفريقية تفاعلية بين إرشادات WHO وإرشادات NICE",
      "مستكشف تفاعلي شفاف للمقاطع ودرجات التشابه الدلالي",
    ],
  },
];
